### ISSUE TITLE
Please make author and tag muting more convenient to use.😍

### ISSUE THREAD

**Issue by gimgimgima6** [asadahimeka/pixiv-viewer-apk#3]
This is the best app I've been looking for and I'm so glad I got to use it. However, I have two suggestions.
It's nice to be able to copy the author's UID, but it's very cumbersome to go into the settings and paste it one by one. It can be more convenient by just long press on the thumbnail of a work, it will ask you if you want to mute the author of this work or some of the tags of this work. Clicking Yes will immediately add this author's UID or tag to the mute list within the app settings. This function is implemented in an app called PxView R, so it is good to refer to. 
It would also be good not to reset how far I scrolled in the search result grid images. When I go in and out of the work page, I have to scroll all over again to the point I scrolled to. 
If these two things are solved, it will be a perfect app. Thank you so much for your hard work.😍

![Screenshot_20231216_155824_Pixiv Viewer](https://github.com/asadahimeka/pixiv-viewer-apk/assets/71699516/30d15c44-2448-4fb4-b7b9-4e068ff4e01d)

**Comment by asadahimeka** [comment]
@gimgimgima6 , thanks for your proposal. 

I spent some time to simply implement the long press blocking function. It has been applied to the web version: https://pixiv.pics. You can try it to see if it meets your needs. I will introduce this feature in the next release of the app version.

First you need to turn on the long press blocking switch in the settings, and then it cannot be used with long press downloading. 

Regarding the page scrolling behavior, it works normally on my side. If yours doesn't work, it may be because you turned on the page transition effect switch, which will cause some problems, or it may be a device compatibility issue. I currently have no spare capacity to fix it.

**Comment by gimgimgima6** [comment]
![da238dc3a982fa7dfa89055279f8fe96](https://github.com/asadahimeka/pixiv-viewer-apk/assets/71699516/d4609664-ed1e-48cf-a2e6-29e6c82c8c6e)
This is the perfect improvement I was hoping for. Thank you so much for such quick feedback.

**Comment by asadahimeka** [comment]
@gimgimgima6 , Merry Xmas ~ 🎄
The longpress blocking feature has been introduced in the [latest app version](https://github.com/asadahimeka/pixiv-viewer/releases/latest) , just have a try~
